### ISSUE TITLE
我想知道如何部署 admin 部分

### ISSUE THREAD

**Issue by wxingheng** [justJokee/vue-ssr-blog#2]
我想知道如何部署 admin 部分

**Comment by wxingheng** [comment]
希望可以提供一些指导

**Comment by sskun** [comment]
部署可以了吗

**Comment by wxingheng** [comment]
可以了  非常感谢🤗🤗




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            1228678518
                            
                            
                                
                                    邮箱：1228678518@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2018年09月09日 04:39，sskun 写道： 部署可以了吗

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/justJokee/vue-ssr-blog","title":"justJokee/vue-ssr-blog","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/justJokee/vue-ssr-blog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sskun in #2: 部署可以了吗"}],"action":{"name":"View Issue","url":"https://github.com/justJokee/vue-ssr-blog/issues/2#issuecomment-419671360"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/justJokee/vue-ssr-blog/issues/2#issuecomment-419671360",
"url": "https://github.com/justJokee/vue-ssr-blog/issues/2#issuecomment-419671360",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [justJokee/vue-ssr-blog] 我想知道如何部署 admin 部分 (#2)",
"sections": [
{
"text": "",
"activityTitle": "**sskun**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sskun",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"justJokee/vue-ssr-blog\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"justJokee/vue-ssr-blog\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/justJokee/vue-ssr-blog/issues/2#issuecomment-419671360"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356208029\n}"
}
],
"themeColor": "26292E"
}
]
